### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PrestigeDox** [yoda-pa/yoda#101]
Allow the bot to understand any format of language: 

Current:
'yoda speedtest'

New:
'yoda do a speedtest'
'yoda can you please do a speed test'

Current:
'yoda define amazing'

New:
'yoda find the definition for amazing'

Just generally allowing versatility for language.

**Comment by moyamanuel** [comment]
I'm not too familiar with Natural Language Processing, but I believe NLP can help us with this task. Is anyone here familiar with Natural Language Processing?

**Comment by manparvesh** [comment]
This will be handled in #61 
So I'm closing this issue
