### ISSUE TITLE
File handler not closed warning

### ISSUE THREAD

**Issue by tirkarthi** [yoda-pa/yoda#107]
I came across this warning in Travis builds. It seems the file handle was not closed in the except block. I don't know why it was opened in the first place and just wanted to report here.

```
/home/travis/build/tirkarthi/yoda/modules/alias.py:22: 

ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/travis/.yoda/alias/alias.txt' mode='w' encoding='UTF-8'>
```

**Comment by manparvesh** [comment]
@tirkarthi thanks for reporting!
