### ISSUE TITLE
Install for use without having to manually clone the repo

### ISSUE THREAD

**Issue by pjz** [yoda-pa/yoda#111]
Pip has had good syntax for directly installing from a git repo for awhile now.  Documenting the usage of it would simplify your user's life.

`virtualenv yodaenv`
`./yodaenv/bin/pip install git+https://github.com/yoda-pa/yoda`

Is a lot less verbose than the previous instructions.

In my case it was even simpler since I use [pipsi](https://github.com/mitsuhiko/pipsi).  I just did
`pipsi install git+https://github.com/mitsuhiko/pipsi#egg=yoda`

...but I'm not sure if encouraging the use of pipsi is in your bailiwick.

**Comment by manparvesh** [comment]
@pjz Hi Paul,
Thanks for the suggestion! I didn't know about that! Will definitely add these instructions to the README.
I think the first style would be better, since most people won't have `pipsi` installed on their systems and it would add an additional step.
