### ISSUE TITLE
Yoda speedtest raising "servers not available" error

### ISSUE THREAD

**Issue by vccolombo** [yoda-pa/yoda#115]
## What are the steps to reproduce this issue?
1. … run yoda speedtest

## What happens?
… Speedtest servers not available

## What were you expecting to happen?
… speedtest to run

## What versions of software are you using?
**Operating System:** …
Ubuntu 18.04

## Notes
[pyspeedtest](https://github.com/fopina/pyspeedtest) has not been updated for 2 years now, and an issue was raised in their repo 1 month ago about this same problem, without any response. I think this package will not be update anytime soon, so I suggest a migration to other one, or to write our own.

**Comment by vccolombo** [comment]
Also I think modules/dev.py line 42 needs to be changed to 
`sys.exit(0)`
for the error to be catch by the tests

**Comment by manparvesh** [comment]
@vccolombo thanks for the feedback!
You're right, `sys.exit(1)` should have been used.

**Comment by Ravi-0809** [comment]
Pull request submitted. Please verify. 
Pull request #123
