### ISSUE TITLE
Add option to modify/delete existing entries

### ISSUE THREAD

**Issue by zuziik** [yoda-pa/yoda#119]
## Feature description:
The modules diary, love, flashcards and others allow the user to set/remember something but not change/delete it. All the data are stored in files and are impossible to remove via yoda CLI (only by directly deleting the files).

I would like to see features to change existing data (e.g. a task set with a typo) or clean them (outdated task list).

- diary clean - remove all completed tasks
- diary mt - modify an existing task
- diary mn - modity an existing note
- diary dt - delete an existing task
- diary dn - delete an existing note
- etc for other modules

## Any ideas on how to implement it?
Add new commands to the existing modules.

**Comment by manparvesh** [comment]
@Man-Jain you can check where the diary entries are saved in the config folder and delete them when these commands are invoked.

**Comment by Man-Jain** [comment]
@manparvesh I was thinking about first giving the user a list of all the dates having tasks and then on choosing the date he will get a list of tasks on that day which he could either delete or update. 
And similarly with notes.

**Comment by manparvesh** [comment]
@Man-Jain :+1:
