### ISSUE TITLE
Yoda crashes when trying to chat under Python 3

### ISSUE THREAD

**Issue by karuvally** [yoda-pa/yoda#127]
## What are the steps to reproduce this issue?
1. Create Virtualenv with Python 3
2. Install Yoda using pip install .
3. Run "yoda chat <random_string>"

## What happens?
The program crashes https://gist.github.com/karuvally/0fd2fc18bfa8b2f47c6b9f82f566872c

## What were you expecting to happen?
A proper reply from the chatbot

## What versions of software are you using?
**Operating System:** Debian GNU/Linux 9.4
**Python:** 3.5.3
**pip:** 9.0.1

**Comment by manparvesh** [comment]
@karuvally thanks for the bug report! Judging from the stacktrace, it seems that a simple check would fix this issue.

**Comment by jekoff** [comment]
If You don`t mind I will try to solve this problem!

**Comment by manparvesh** [comment]
@jekoff sure! I'd be happy to receive a PR

**Comment by jekoff** [comment]
@manparvesh I also find the same problem in food module. Should i create a new issue and then fix it there?
