### ISSUE TITLE
Yoda crashes when trying to run suggest_drinks 

### ISSUE THREAD

**Issue by jekoff** [yoda-pa/yoda#131]
## What are the steps to reproduce this issue?
1. Create Virtualenv with Python 3
2. Install Yoda using pip install .
3. Run "yoda food suggest_drinks"

## What happens?
The program crashes https://gist.github.com/jekoff/85eee55f03151fb5838c2d80f975ffee

## What were you expecting to happen?
yoda should return a drink recipe for suggest_drinks command

## What versions of software are you using?
**Operating System:** Elementary OS 0.4.1 Loki
**Python version:** 3.5.2

**Comment by manparvesh** [comment]
@jekoff thanks for reporting!
The tests were passing, but I think we need thorough tests for problems like this.

**Comment by jekoff** [comment]
@manparvesh actually travis CI show me the error when i did the previous PR, and now it show that everything is ok... Hm...

**Comment by manparvesh** [comment]
@jekoff yeah, I saw that too. But then I reran your PR build and everything worked fine. Probably some problem with the service
