### ISSUE TITLE
yoda chat inspire doesn`t work

### ISSUE THREAD

**Issue by jekoff** [yoda-pa/yoda#133]
## What are the steps to reproduce this issue?
1. run yoda chat inpires with python3

## What happens?
yoda crashes https://gist.github.com/jekoff/07545a3a59ae13637cc87292bf44cbe0

## What were you expecting to happen?
get a random quote

## What versions of software are you using?
**Operating System:** elementary OS 0.4.1
**Python Version:** 3.5.2

**Comment by manparvesh** [comment]
@jekoff thanks for the report.
I guess the project became too big too quickly and a lot of things may be unstable :sweat:
