### ISSUE TITLE
Google url shortener is being replaced

### ISSUE THREAD

**Issue by tsehori** [yoda-pa/yoda#135]
## Feature description:
The Google url shortener service is being [transitioned to FDL](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html). Indeed there is some time until the transition is complete (March 2019) but I guess it's better to mention early on.

## Any ideas on how to implement it?
Either switch to a different url shortener or use the [FDL APIs](https://firebase.google.com/docs/dynamic-links/create-links) suggested by Google.

**Comment by divyamsingh13** [comment]
@manparvesh To make this transition FireBase API key will be required.

**Comment by manparvesh** [comment]
Fixed in #136
