### ISSUE TITLE
"modules" module is not being found

### ISSUE THREAD

**Issue by akhilPotla97** [yoda-pa/yoda#14]
*I am new to open source and have found this error when trying to run my local copy of "yoda". I am posting partly to see if there are mistakes in my running of this and also because I would be happy to work on this issue. 

Reproduce the bug:
1. git clone https://github.com/yoda-pa/yoda
2. virtualenv venv
3. . venv/bin/activate
4. pip install .
5. yoda

============

The console outputs an error "ImportError: No module named modules".

The console says this happens in: 
File "/home/akhil/open_source/yoda/venv/local/lib/python2.7/site-packages/yoda.py", line 4, in <module>
    from modules import *

Possible solution:
So I think the issue here is that when Python searches for a file it only looks with in the current directory, and the "yoda.py" that is being run is not in the top most directory in the repository. It exists within the "/venv/local/lib/python2.7/site-packages/" directory; however, the "modules" sub-directory needs be accessed from the "yoda" main directory. 

Using: version 0.1.0 on Ubuntu 16.04

**Comment by akhilPotla97** [comment]
@manparvesh please take a look at this!

**Comment by manparvesh** [comment]
Hi,
is there any error in the installation?

**Comment by akhilPotla97** [comment]
import click
import chalk
import sys
**_sys.path.insert(1, "/home/akhil/open_source/yoda")_**
from modules import *


I added the code that I bolded to "venv/local/lib/python2.7/site-packages/yoda.py" file. And when I ran the  "yoda" command I am getting a Usage Menu.

**Comment by manparvesh** [comment]
Yes, this line fixes the issue. But instead of **"/home/akhil/open_source/yoda"**, it's better to use **os.getcwd()**. Since this is only a one-line fix, I am committing it myself, if you don't mind.

**Comment by akhilPotla97** [comment]
Cool.
