### ISSUE TITLE
Recipe suggestion

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#140]
## Feature description:
As a part of the food module, suggest random recipes

## Any ideas on how to implement 
1. For a beginning point, one can use a public API to get a random recipe every time
1. On top of that, one can also add some filters, if possible, based on the user's interests

**Comment by slin63** [comment]
I can take this.

**Comment by manparvesh** [comment]
@slin63 
Sure! I'd be glad to review your PR!
