### ISSUE TITLE
Document IP lookup feature

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#141]
The `iplookup` command finds the location of an IP address you input. This was contributed in the PR: #139.

**Things to be added:**
- [ ] update readme with the command and a typical output
- [ ] update README to add LICENSE for the use of the database

**Comment by slin63** [comment]
I can take this also,

**Comment by manparvesh** [comment]
@slin63 
Sure! I'd be glad to accept your PR!

**Comment by slin63** [comment]
PR Here: https://github.com/yoda-pa/yoda/pull/160
