### ISSUE TITLE
Github daily summary

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#147]
The user should be able to get a summary of their activity on GitHub, including their commits, issues, PRs, etc. One can use the GitHub API for this.

**Comment by siejqa** [comment]
I'd like to work on this :smile:

**Comment by manparvesh** [comment]
@siejqa 
Sure! I'd be glad to review your PR!

**Comment by siejqa** [comment]
@manparvesh 
I've submitted a PR for you to review - PR #185  - it's still missing tests and documentation update, but wanted to know if it needs any major rework :). I decided to use the pyGithub library as it was already included in the _requirements.txt_.

**Comment by manparvesh** [comment]
@siejqa judging solely from the code can be difficult, but I think when you add some tests I would be able to understand better. I took a quick look and the code looks fine to me
