### ISSUE TITLE
images to ascii art

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#148]
## Feature description:
Convert an image to ascii art

## Example implementations on the internet
- https://www.hackerearth.com/practice/notes/beautiful-python-a-simple-ascii-art-generator-from-images/
- https://gist.github.com/cdiener/10491632

**Comment by DragonGhost7** [comment]
Interesting it is, will do it I

**Comment by manparvesh** [comment]
@DragonGhost7 
Sure! I'd be glad to receive your PR!

**Comment by DragonGhost7** [comment]
Done, please check #169

**Comment by DragonGhost7** [comment]
Hello @manparvesh,
I made the feature, but my coverage tests are failing.
Being kinda new to code coverage, i though it would happen.
How would i write coverage for newly added features?
If you could help would be nice.

**Comment by manparvesh** [comment]
@DragonGhost7 you will need to write some tests for the command you added. You can take a look inside the tests folder to get an idea of how to write tests.
