### ISSUE TITLE
cipher implementations

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#150]
## Feature description:
This can be another learning project for someone interested in cryptography. The user should be able to encrypt and decrypt text using different ciphers.

- [x] add ciphers
- [x] add tests for ciphers
- [x] add README entry

**Comment by hargoniX** [comment]
I'd like to implement a few ciphers for this.

**Comment by V1NAY8** [comment]
I am ready to contribute ciphers..
Is there a list which are to be added.
Or shall Contribute any of the cipher?

**Comment by manparvesh** [comment]
@hargoniX @V1NAY8 you can take a look at this list and contribute any cipher you like:
http://practicalcryptography.com/ciphers/classical-era/

**Comment by V1NAY8** [comment]
# Ready with a cipher should check functionality
## What files are to be edited 
- Create cipher.py in  modules folder
- in yoda.py adding its own function
and ??
- Shall I fork and create a branch and then make pull request???

**Comment by hargoniX** [comment]
My PR, does (as mentioned in it too) not add all the ciphers, once this gets merged anyone else can add his own ciphers on top of it.

**Comment by manparvesh** [comment]
Anyone who is interested in contributing to this issue can take a look at the unchecked tasks in the issue description. Some cipher implementations were added to the project in #178, but more implementations are welcome too!
