### ISSUE TITLE
whois search

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#154]
whois information for a domain name, if that is something that can be fetched using some API. I have not explored this.

**Comment by athulpn** [comment]
I would like to work on this issue. And yes there is an API available for it.

**Comment by manparvesh** [comment]
@athulpn Sure! I'd be glad to review your PR!
Simply showing the whois info should be fine

**Comment by Khukhuna** [comment]
Can I use BeautifulSoap to scrape the **https://www.whois.com/whois/** ? Because there is no free API that we can use :confused: If there is, please let me know :smiley:

**Comment by Khukhuna** [comment]
@manparvesh

**Comment by manparvesh** [comment]
@Khukhuna sorry for late reply, I got busy.
Did you try this API? It seems usable in our case: https://www.domaintools.com/resources/api-documentation/whois-lookup/

**Comment by Khukhuna** [comment]
You need to sign up on website to get data from that API, which costs $99/mo.

**Comment by manparvesh** [comment]
@Khukhuna oh okay. Then I guess your approach would be better.
And thanks for your interest in the project :smile:
