### ISSUE TITLE
mp3 cutter

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#157]

**Comment by Thelta** [comment]
I would like to take this issue.

**Comment by manparvesh** [comment]
@Thelta 
Sure! I'd be glad to review your PR!

**Comment by Khukhuna** [comment]
Hello  :smile:  

can i work on this issue? It's been 6 days since last comment. :smiley_cat:
if yes, can i use [**pydub**](https://github.com/jiaaro/pydub) library? :fire:

**Comment by manparvesh** [comment]
@Khukhuna sure :smile:

**Comment by Khukhuna** [comment]
can i add simple **.mp3** file in **/resources** folder for tests :question: :smile: I can't think of any other way to test this functionality.

**Comment by manparvesh** [comment]
@Khukhuna sure, you can add 2 or 3 mp3 files to test!
