### ISSUE TITLE
lease list

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#159]
Keep a list of all the things that you have lent to/from people.

**Comment by theishshah** [comment]
Would like to take on this issue

**Comment by manparvesh** [comment]
@theishshah 
Sure! I'd be glad to review your PR!

**Comment by manparvesh** [comment]
@moyamanuel I don't think he is, so you can!

**Comment by groovychoons** [comment]
Did @moyamanuel get anywhere with this? If not I'd like to give it a go.

**Comment by manparvesh** [comment]
@groovychoons sure go ahead

**Comment by groovychoons** [comment]
I've submitted a pull request with this feature.

**Comment by groovychoons** [comment]
#251
