### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#16]
Description:
-------------------
Add automated tests to the project. Currently, the Travis build simply runs pytest, but since there are no tests, it passes.

This task will take a considerable effort.

#### Checklist:
- [x] chat
- [x] dev
  - [x] speedtest
  - [x] url
- [x] diary
  - [x] notes
  - [x] tasks
    - [x] analysis
- [ ] learn
  - [x] vocabulary
  - [ ] flashcards
  - [x] define
- [ ] life
  - [ ] reading list
  - [ ] ideas
- [x] love
- [x] money
- [ ] setup
- [x] feedback
- [x] util

**Comment by manparvesh** [comment]
For now, #36 fixes the failing travis build. I replaces `pytest` with `python setup.py test`, and it checks if the setup builds properly.  
We can use `pytest` in the future when the tests are written properly

**Comment by systemplado** [comment]
I'm interested in adding some tests. We can use the official testing [provided by Click](http://click.pocoo.org/5/testing/). Should we place the tests inside the modules or a separate directory?

**Comment by manparvesh** [comment]
@systemplado that's cool! :smile: We should use that. We should place the tests in a different directory, since it's not a module.

**Comment by manparvesh** [comment]
As suggested by @systemplado, I have started writing tests for `yoda` using `click.testing`. If someone is interested to contribute, they can take a look at the sample test file that I have written: [test_speedtest.py](https://github.com/yoda-pa/yoda/blob/b5ecb458cd8c961e5dd388b0607359a470e5b165/tests/dev/test_speedtest.py)

**Comment by manparvesh** [comment]
I think it is okay to believe that the test coverage is fine for the project. However, I think it still needs improvement, so this will be continued in #71  and I will close this issue
