### ISSUE TITLE
yoda chat return html code (error)

### ISSUE THREAD

**Issue by MatkoUSKO** [yoda-pa/yoda#17]
What are the steps to reproduce this issue?
-------------------------------------------
just type yoda chat how are you or something

What happens?
yoda answers just with html (error code).
here it is
Yoda speaks:
`<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>`

What versions of software are you using?
macOS 10.12.6

**Comment by ujjaldas1997** [comment]
@MatkoUSKO, I think your internet connectivity is weak, or disconnected. I got the same error and after checking connectivity, this error goes off.

**Comment by manparvesh** [comment]
@MatkoUSKO @ujjaldas1997 there is some issue with the Mashape key while using the `Yoda speaks API`. I am removing that part for now. Will return a simple response.
