### ISSUE TITLE
People manager beautify output 

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#189]
Current output structure: https://github.com/yoda-pa/yoda#people
Feature added in: #184 

### Things to improve
- [ ] `yoda people status` command should show a structured output instead of json
- [ ] update error message when likes not exist: [code](https://github.com/yoda-pa/yoda/blob/master/modules/people.py#L200)
- [ ] update error message when notes do not exist: [code](https://github.com/yoda-pa/yoda/blob/master/modules/people.py#L226)
- [ ] update line [52](https://github.com/yoda-pa/yoda/blob/master/modules/people.py#L52) and [249](https://github.com/yoda-pa/yoda/blob/master/modules/people.py#L249)

**Comment by c-shekhar** [comment]
@manparvesh, looks like small updates. Taking this on!
