### ISSUE TITLE
mp3cutter | Terminal throws error when given start point is greater than song length.

### ISSUE THREAD

**Issue by Khukhuna** [yoda-pa/yoda#192]
**Module:** dev
**Command:** mp3cutter
Terminal throws error when given start point is greater than song length.

<img src="https://user-images.githubusercontent.com/37747169/46717893-7ec95400-cc7a-11e8-9d60-2436f6ddf452.png" width=50%>

## What are the steps to reproduce this issue?
1. Install yoda
2. run ```yoda dev mp3cut "path/to/music.mp3" 5000 10 ```

## What happens?
Terminal throws error when given start point is greater than song length.

## What should we do?
```yoda dev mp3cut [PATH] [Start] [End] ```
- Check and make sure that start point is less than length of music file
- Check and make sure that start point is less than end point.

## What versions of software are you using?
**Operating System:** Ubuntu 16.04

**Comment by Khukhuna** [comment]
Sorry, I forgot these safe-checks when i implemented mp3cutter command :cry: 
I'd like to work on this issue.

**Comment by manparvesh** [comment]
@Khukhuna it's okay, thanks for reporting and providing a solution!
