### ISSUE TITLE
Reading list

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#20]
Feature description:
-------------------
Feature to add a reading list, where the user can add articles, books, etc to their lists, and read whenever they want in the future.

**Comment by systemplado** [comment]
Could this be added to ```module:diary``` instead? I wanted to help but I think creating a new module is quite confusing for me. If it cannot be, I'll try my best to do a new module. 😁

**Comment by manparvesh** [comment]
@systemplado if you don't feel much confident in making a new module, you can work on a different module for now, and when this module is made, you can get back to this. :smile:

**Comment by systemplado** [comment]
Okay, I'm up to the challenge to write a module.

I'm planning to do the following:
* Follow how the diary module works
* It should have the following commands
  * ```rlist```: shows the reading list
  * ```ra```: adds something to the list
  * ```ro```: opens an article using ```xdg-open``` or maybe something more portable
* A reading list should have
  * A title
  * An author
  * Type/kind (book, journal, website, blog, etc) *should I even add this?*
  * Tags (for searching/filtering in the future)
  * Path (either URL or file path)

What do you think?
