### ISSUE TITLE
Setup docker for yoda

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#209]
Let's create a containerized option for users to test `yoda` without disturbing their development environment. Below is a minimal environment suggested by @meanmachin3:
```dockerfile
FROM python:3.5-alpine
WORKDIR /usr/src/app
ADD requirements.txt .
RUN apk add --no-cache --virtual .build-deps gcc musl-dev
RUN pip install -r requirements.txt
RUN apk del .build-deps gcc musl-dev
COPY . .
RUN pip install .
```
To run this, use: `docker run --rm -it --name yoda yoda:latest yoda chat Hello`

Some improvements that could be incorporated to his solution:
- [ ] add option to use different Python versions

**Comment by sr6033** [comment]
I will see if I can add that.

**Comment by sr6033** [comment]
@manparvesh Do you need it completely dockerized and uploaded in the public hub?

**Comment by manparvesh** [comment]
@sr6033 it would be okay if only the docker configuration is added. Regarding uploading to docker hub, I will do that. I have already created a repo for this project (https://hub.docker.com/r/yodapa/yoda/) and will push to it once docker config is added.

**Comment by thornycrackers** [comment]
This can be closed

**Comment by manparvesh** [comment]
@thornycrackers this issue is open because the `option to use different Python versions` is still pending

**Comment by meanmachin3** [comment]
Do you want python support for every version or ability to be able to switch between python2 and python3 works ?

We can pass an ENV variable using `-e PYTHON_VERSION='3.6'` and then using an apline image, we can dynamically load a python version specified in ENV. I can take this up if no one else is working on it

**Comment by meanmachin3** [comment]
Not really sure if we need to support python2. We could focus only on python3 since python2 will be not be maintained from 2020.

**Comment by manparvesh** [comment]
@meanmachin3 you're right. I guess we don't need this issue. Closing it.
