### ISSUE TITLE
Idea list

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#21]
Feature description:
-------------------
An encrypted list where one can store their ideas, with descriptions. For more ideas that can be added to this list, one can take a look at [this repository](https://github.com/IdeaTrackerPlus/IdeaTrackerPlus).

**Comment by ujjaldas1997** [comment]
Hello @manparvesh , 
I had a quick look at the [app](https://play.google.com/store/apps/details?id=appbox.gameideas), and like to add idea list, which will be of basic operations I have thought to add with encryption
1. add
2. remove
3. show

Can you assign this issue to me?

**Comment by manparvesh** [comment]
@ujjaldas1997 sure you can start working on this and send me a PR

**Comment by manparvesh** [comment]
@ujjaldas1997 since you have written the basic implementation of this, if possible, please also write the documentation for the functions (just one line description is sufficient) and send me a PR if you have time. Thanks!
