### ISSUE TITLE
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work

### ISSUE THREAD

**Issue by sr6033** [yoda-pa/yoda#212]
## What are the steps to reproduce this issue?
1. Followed the install steps in CONTRIBUTING.md to install yoda.

## What happens?
![image](https://user-images.githubusercontent.com/15799589/47256233-fd539c00-d499-11e8-8a63-b2a1bd38c807.png)

## What versions of software are you using?
MacOS High Sierra

**Comment by manparvesh** [comment]
@sr6033 can you try installing `libav-tools` to your system?

**Comment by sr6033** [comment]
Thanks @csaranbalaji
