### ISSUE TITLE
Proposal: Use black for code formatting/linting

### ISSUE THREAD

**Issue by thornycrackers** [yoda-pa/yoda#216]
Hello!

I see that there are quite a few hacktoberfest issues out for the repo and there are quite a few people interested in contributing to the project. I was wondering if having a consistent code style across the project would be a valuable to the project and if so I would propose using black:

https://github.com/ambv/black

Or if others would like to propose a different styling that would be good too. What ever is chosen as the standard could be built into the Docker setup to help people new to the project make sure their contributions are following the linting style.

**Comment by manparvesh** [comment]
@thornycrackers that's a great idea!

**Comment by mondaini** [comment]
@manparvesh may I have this?
