### ISSUE TITLE
Load modules only when they are called

### ISSUE THREAD

**Issue by ArthurCueio** [yoda-pa/yoda#241]
**What would you like to be added**:
Load the necessary modules (utils, config, setup, etc...) when yoda starts. And load the modules that contains the commands only when that command is called
**Why is this needed**:
This will make yoda load faster.
When trying to run "yoda" on a low end laptop the delay between the time enter is pressed and the help message shows up is on average 7 seconds. When a lot of commands needed to be ran those 7 seconds can get very annoying.

/kind feature

**Comment by manparvesh** [comment]
@ArthurCueio thanks a lot for reporting this! Would be happy to receive a PR if anyone is interested.

**Comment by ArthurCueio** [comment]
This issue could also be more easily addressed by moving some code that runs when modules get imported to inside a setup method or something similar. And call that when the command is called.

**Comment by jrbr** [comment]
Hello, I would be happy to begin work on this
