### ISSUE TITLE
Importerror: bs4 not found

### ISSUE THREAD

**Issue by muzz1497** [yoda-pa/yoda#256]
**What happened**:
I forked yoda. I created a virtualenv and installed pip editable and everything was successful. When I type yoda I get:

ImportError: No module named bs4

**What you expected to happen**:
Yoda to start

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Yoda version (use `yoda version`):  0.40
- OS (e.g. from /etc/os-release): Windows 10 64bit
- Kernel (e.g. `uname -a`):
- Others: Python 2.7

/kind bug

**Comment by manparvesh** [comment]
@muzz1497 this should be fixed now. Please try again. If not fixed, I would suggest using Python 3. I am closing this issue for now
