### ISSUE TITLE
Travis build checker failing .travis.yml

### ISSUE THREAD

**Issue by yuxuwu** [yoda-pa/yoda#26]
I'm not entirely sure about this, but it seems like my pull requests are failing because Travis fails when attempting to run the "py.test" command to check for passing builds. 
Might removing the script phase, or adding in a temporary testing file solve the issue?
![0072baac95c63e6a34b74d5b9ce2fd50](https://user-images.githubusercontent.com/22068412/31185383-c85d5f58-a8f9-11e7-97e0-17e53533c1a5.png)

**Comment by yuxuwu** [comment]
Okay, so apparently pytest was just being executed incorrectly, changing "script: py.test" to "script: pytest" in .travis.yml should fix the problem.

**Comment by yuxuwu** [comment]
Just to add, the Travis build will fail if no test cases are run, returning exit code 5.

**Comment by manparvesh** [comment]
@yuxuwu This is already on the roadmap(#16), so I am closing this issue.
