### ISSUE TITLE
Make the code pep8/pyflakes compliant

### ISSUE THREAD

**Issue by sachet-mittal** [yoda-pa/yoda#27]
Feature description:
-------------------
It would be better if code be pep8/pyflakes compliant

Any ideas on how to implement it?
---------------------------------
either run autopep8 on the code or manually fix the errors.

Any other comments?
-------------------
I would like to take this up.

Any feedback on the project?
-------------------
The project looks cool.

**Comment by manparvesh** [comment]
@sachet-mittal sure

**Comment by sachet-mittal** [comment]
@manparvesh Submitted the pull request: https://github.com/yoda-pa/yoda/pull/35

But tests are failing. It seems https://github.com/yoda-pa/yoda/pull/34 needs to be merged first.

**Comment by manparvesh** [comment]
Hi @sachet-mittal this looks good to me, but there have been some changes in the project recently. Can you please run autopep8 again and submit a different pull request? I closed #35 for now.

**Comment by sachet-mittal** [comment]
@manparvesh Yeah Sure I can do that. But a query:
For this do i need to fork again?

**Comment by manparvesh** [comment]
@sachet-mittal  yeah I think so. Maybe you can update your fork. Google will have better answers

**Comment by shubhras01** [comment]
Is this issue solved ?

**Comment by sachet-mittal** [comment]
I am working on it.
Didn't get time to resolve the last comment for the last couple of days.

**Comment by d-grossman** [comment]
sound like you really want a pep8 precommit hook
