### ISSUE TITLE
Error message when trying to use yoda chat when system is offline

### ISSUE THREAD

**Issue by saurabh-kumar-vit** [yoda-pa/yoda#39]
If I try to use the ```yoda chat``` feature when my system is offline, it hits me with a big python error message about socket error
```socket.gaierror: [Errno -2] Name or service not known```

What are the steps to reproduce this issue?
-------------------------------------------
1. Go offline
2. Try any of the yoda chat commands

What happens?
-------------
There is no error checking at ```response = request.getresponse().read()```, so when it does not get a proper response it throws the error. 

How to solve it
--------------
We can easily solve this issue by using try catch blocks to encapsulate the part where we make the request. So when ever the request fails we can give the user a friendly reminder to go online instead of the error message.

I would love to implement this and contribute to the project.

**Comment by manparvesh** [comment]
@saurabh-kumar-vit nice catch! Sure, you are welcome to contribute! :smile:

**Comment by saurabh-kumar-vit** [comment]
I have pushed a PR please review it.
