### ISSUE TITLE
Set goals and do analysis

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#5]
What should happen?
-------------------
- User should be able to set a target / goal (can set a date, or just weekly / monthly).
- One should be able to check their goal and their set dates for completion
- One should be able to set tags in their daily tasks added to the diary which automatically add the task to the goal (by using hashtags?)

Any ideas on how to implement it?
---------------------------------
- Create a different folder with the config file containing the names of the goals with their completion status and deadlines.
- Create a different file for every goal (keeping in mind the filename conflicts) and add the tasks to it

**Comment by raghav710** [comment]
Can i submit an initial working version for this with the following features?
* Set a goal and date
* View goal and specified completion dates in chronological order

**Comment by manparvesh** [comment]
@raghav710 sure

**Comment by zuziik** [comment]
What is the current state of the issue? Anyone working on that? If this is still open, I'd like to help.

**Comment by manparvesh** [comment]
@zuziik the issue is still open. You're welcome to contribute!

**Comment by zuziik** [comment]
Perfect, you can count on me! I will dig into the source code, look around and start working on the issue. I will keep you updated ;)

**Comment by zuziik** [comment]
Hey! I submitted an implementation. I will be open to any discussions/improvements.
Will add tests soon.
