### ISSUE TITLE
Notes with titles

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#51]
Feature description:
-------------------
Option to add a note which is kind of an article, with title and content, and the user can add notes to it.

**Comment by Dheeraj1998** [comment]
Hey! I would love to work on this. Some help on getting started and I will do it 😄

**Comment by manparvesh** [comment]
@Dheeraj1998 thanks for your interest! :smile: Just go through the code, you can let me know if you don't understand something.

**Comment by jahenkor** [comment]
Is this issue still up for grabs? I'd love to work on this issue if this is the case.

**Comment by manparvesh** [comment]
@jahenkor yes, it's still unresolved! thanks for your interest!

**Comment by raghukokku** [comment]
Hey Man Parvesh,
I am new to this part of the open source world. I am willing to contribute in this effort. Could you please tell me how to proceed with this issue.

**Comment by manparvesh** [comment]
Hi @raghukokku , thanks for your interest. You can take a look at the [contributing guidelines](https://github.com/yoda-pa/yoda/blob/master/.github/CONTRIBUTING.md)

**Comment by raghukokku** [comment]
I looked at the contributing guidelines and tried to setup. Looks like i need access to the project to clone.

**Comment by manparvesh** [comment]
@raghukokku no, you don't. Since you have already cloned the repo, just git clone your repo instead of the original one. In your case, do:
```
$ git clone https://github.com/raghukokku/yoda
```

**Comment by raghukokku** [comment]
Got it. Thank you.

**Comment by rkokku** [comment]
i followed the instructions and did the setup but the last step failed. When i keyed in yoda, i get command not found.Did i miss anything?

**Comment by manparvesh** [comment]
@rkokku can you post the error message here?

**Comment by rkokku** [comment]
Raghus-MacBook-Pro:projects rkokku$ ls
venv	yoda
Raghus-MacBook-Pro:projects rkokku$ cd yoda
Raghus-MacBook-Pro:yoda rkokku$ ls
CODE_OF_CONDUCT.md	README.md		config.py		modules			resources		tests			yoda.egg-info
LICENSE			TODO.md			logo.png		requirements.txt	setup.py		util.py			yoda.py
Raghus-MacBook-Pro:yoda rkokku$ yoda
-bash: yoda: command not found
Raghus-MacBook-Pro:yoda rkokku$

**Comment by manparvesh** [comment]
@rkokku no not this one. The error you got while installing

**Comment by rkokku** [comment]
checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/q0/fd931jps1dj3f9wgqzzf_66m0000gn/T/pip-build-1BZzdP/pycrypto':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q0/fd931jps1dj3f9wgqzzf_66m0000gn/T/pip-build-1BZzdP/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/q0/fd931jps1dj3f9wgqzzf_66m0000gn/T/pip-build-1BZzdP/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/q0/fd931jps1dj3f9wgqzzf_66m0000gn/T/pip-build-1BZzdP/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/q0/fd931jps1dj3f9wgqzzf_66m0000gn/T/pip-build-1BZzdP/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/q0/fd931jps1dj3f9wgqzzf_66m0000gn/T/pip-pqq1ZR-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/q0/fd931jps1dj3f9wgqzzf_66m0000gn/T/pip-build-1BZzdP/pycrypto/

**Comment by manparvesh** [comment]
@rkokku I think you need `python-devel` package for OSX. Please take a look at [this link](https://stackoverflow.com/a/32578175)

**Comment by raghukokku** [comment]
Thank You. Will take a look.

**Comment by rkokku** [comment]
Works now. Thank You. Looks like i had two versions of python 2.7 and 3.6.3 that was causing the issue. I ran the command 

brew uninstall python to uninstall python.

and then ran the commands needed for setup and the setup ran successfully.

**Comment by rkokku** [comment]
I went through the code and ran some commands to get a feel of the tool. Below is my understanding of this feature.
1) This feature should provide the ability to add notes for example the command would be "yoda notes"
2) The user will be typing in the content with the title.

I have some questions on this feature.

1) What is the main purpose of this feature? Once user adds notes, will he publish somewhere or send it to anyone?
2) Is there a limit on the content?
3) Where will the article be saved?
4) Do we filter the article for any specific type of language?
5) Does the article need print, email, export features?

**Comment by rkokku** [comment]
After going through the diary module, i came up with the below code snippet. Is this what you are looking for.


def article():
        """
        new article
        """
        chalk.red('Input the title')
        title=raw_input().strip()
        chalk.blue('Input the content')
        content = new_note()

**Comment by Man-Jain** [comment]
@manparvesh, I would like to work on this issue.

**Comment by manparvesh** [comment]
@Man-Jain sure, I'm open to receiving PRs

**Comment by Man-Jain** [comment]
@manparvesh In which should this feature be implemented.

Will it be a improvement of the already present note feature in the diary module or a new function in some other module will be created?

**Comment by manparvesh** [comment]
@Man-Jain it will be a improvement of the already present note feature in the diary module

**Comment by Man-Jain** [comment]
@manparvesh Okay I am working on it.
