### ISSUE TITLE
I'm trying to run this on Windows and I think i'm missing something

### ISSUE THREAD

**Issue by BrianMwangi21** [yoda-pa/yoda#58]
I have forked and cloned the project locally.
I have also installed all the packages needed and created the virtual environment.
But when I run `$ yoda` using GitBASH or GitCMD, it doesn't run.
I'm I missing something ?

![untitled](https://user-images.githubusercontent.com/14116447/33804368-4bda246c-ddb4-11e7-8865-3d4076f5d6e2.jpg)

**Comment by manparvesh** [comment]
can you please post the error message here?

**Comment by manparvesh** [comment]
@BrianMwangi21 you need to run `pip install --editable .` after running starting the `virtualenv`

**Comment by BrianMwangi21** [comment]
Still did not work

![untitled](https://user-images.githubusercontent.com/14116447/33805507-24b193ae-ddcb-11e7-8457-9b6ddcfa39a3.jpg)

**Comment by manparvesh** [comment]
Probably because you're using Python 3.5. You need 2.7 for this

**Comment by BrianMwangi21** [comment]
so i do have to change?

**Comment by manparvesh** [comment]
yes
