### ISSUE TITLE
Keyboard shortcuts 

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#60]
Feature description:
-------------------
There should be a feature to get and search keybindings for different software packages and tools, like `eclipse`, `vim`, etc.

- The user should be allowed to add more lists
- They can search for keybindings in a list
- [big] use natural language queries to understand and reply appropriate key-binding for the query
- [todo] divide this into smaller tasks

Any ideas on how to implement it?
---------------------------------
- Add this in dev module
- Import lists as csv files
- while searching for what a keyword does, instead of accurate match, use partial search as well

**Comment by c-shekhar** [comment]
@manparvesh, I am starting to work on this.
Starting with first two points in feature description.
