### ISSUE TITLE
yoda inspire

### ISSUE THREAD

**Issue by Lightyagami1** [yoda-pa/yoda#64]
Feature description:
showing quote to the user which will be inspirational

Any ideas on how to implement it?
using https://forismatic.com/en/api/

**Comment by Nisha-Kapoor** [comment]
@Lightyagami1 I would like to work on this task

**Comment by Nisha-Kapoor** [comment]
Is the quote based on some input provided by the user?

**Comment by Lightyagami1** [comment]
@Nisha-Kapoor you can definitely do it.
I was thinking of having one quote for a day, storing it once it has been fetched rather calling API again. For next day this will be discarded and then a new quote will be fetched and stored in its place.
About type of quote, in my plan I was thinking to have a single command such as "yoga inspireme" and this will fetch some quote related better lifestyle or such, like one a knowledgeable person like yoga would have spoke

**Comment by QuanTakeuchi** [comment]
Hi. Is anyone still working on this? Would like to contribute here.
