### ISSUE TITLE
Add gif demos

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#74]
Since there are many features in yoda, it'll be better to have gif demos in the readme showing all the features.

**Comment by AntonTymczenko** [comment]
youtube video be better would with some voice explanations :)

**Comment by manparvesh** [comment]
@AntonTymczenko yeah, video may be a better option, but I don't have that good of a voice haha. I've added gif demos for now

**Comment by AntonTymczenko** [comment]
@manparvesh you could outsource it. Write down the text and give it somebody to record. :-)

**Comment by manparvesh** [comment]
@AntonTymczenko thanks fir the suggestion :) I'll create an issue and if someone is interested, they can create a video for this project
