### ISSUE TITLE
colored output not working 

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#79]
## What are the steps to reproduce this issue?
1. Run any command that uses `chalk` to output

## What happens?
Nothing is displayed

## What versions of software are you using?
**Operating System:**  Ubuntu 16.04

## Suggestions on how to fix
Find a different library to output colored text or just use print statements (in this case, click.echo would be better than print statements)

**Comment by skcse** [comment]
@manparvesh 
We can use " click.echo(chalk.red('foo')) " instead of using " chalk.red('foo') ".
Reference--[https://pypi.python.org/pypi/pychalk](Reference)
Using the above code, I have tried on setup.py ( yoda setup new ) that works !!

**Comment by manparvesh** [comment]
Fixed in #81
