### ISSUE TITLE
setup command not working 

### ISSUE THREAD

**Issue by skcse** [yoda-pa/yoda#80]
For installing yoda as mentioned in 'contribution.md'
# For bug reporting
## the steps to reproduce this issue?
1. $ git clone https://github.com/yoda-pa/yoda
2. $ cd yoda
3. $ virtualenv -p /usr/bin/python2 venv
4. $ . venv/bin/activate
5. $ pip install .
6. $ yoda

## What happens?
1. After install i used a command "yoda chat hi"
it works yeh!
2. then i used a comman "yoda setup new"
this command keeps on running until i close it.
same happens with command "yoda money setup"

operating system - ubuntu 16.04

**Comment by manparvesh** [comment]
@skcse Hi,
Thanks for reporting this. Actually, the text is displayed but it is shown using a colored text, and for some reason the package that I am using for displaying colored text is no longer working. This was realised in #79, so it will be fixed using that issue. I will close this, but thank you for reporting this.
You can see more details for how to fix this issue in #79 and you are welcome in case you would like to contribute in fixing this. Thanks
