### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#84]
## Description
After changing `chalk.<color>` to `click.echo(chalk.<color>)`, some tests are failing because of difference in the outputs

**Comment by skcse** [comment]
@manparvesh 
can you give me the name of some failing tests, so that I can start from that

**Comment by manparvesh** [comment]
@skcse the test for `speedtest` in `url` module is failing. You can see more details in the travis build: https://travis-ci.org/yoda-pa/yoda
Also, when fixing the tests you can test on your local system using `python setup.py test`
