### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#85]

**Comment by tirkarthi** [comment]
To add to this. I tried testing it in python 3 using `python setup.py install` and I found some dependencies to be incompatible.

* Unirest - [Github issue](https://github.com/Kong/unirest-python/issues/43)
* poster - Dependency of unirest. [Github issue](https://github.com/JeremyGrosser/python-poster/pull/2)

**Comment by tirkarthi** [comment]
I have made a fork compatible with Python 3 at https://github.com/tirkarthi/unirest-python . You can use it as a git based dependency. It doesn't work for gzip based files for now. You can find a Python 3 fork for poster at https://github.com/tirkarthi/python-poster.
