### ISSUE TITLE
Analyzing data before getting a new word

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#9]
Feature description:
-------------------
In the `vocabulary` module, a new word is chosen at random, but I want it to analyze the previous accuracy results of the words and get a word accordingly. 

Any ideas on how to implement it?
---------------------------------
For example, we can set the weights for the words used, and sometimes words are chosen from there and sometimes new words are shown.

**Comment by akhilPotla97** [comment]
I would like to take up this issue. Could you assign it to me?

**Comment by manparvesh** [comment]
Sure! You can work on this 👍

**Comment by Griffintaur** [comment]
we can use the sigmoid function $$  \frac{1}{1+e^{-x}} $$ where x is  the person's score
which can be computed by multiplying relative hardness of the word on the predefined scale and score allocated for getting it write i.e $$ x=\sum  {h* correct} $$

**Comment by Griffintaur** [comment]
if it is still open I can take it up

**Comment by manparvesh** [comment]
@Griffintaur thanks for your interest! Yes, this issue is still open so you can work on it.

Your suggestion sounds good to me. I am excited to see how you implement it!

There are a few things you should know though:
- The data set of the words doesn't have a predefined scale, so it updates the scale (with initial values all set to 0) every time a word is used.
- There are a few hit parade lists that are usually asked frequently in exams like GRE etc., so the words in these lists can be considered as the words with a higher priority than the normal ones. The words in beyond hit lists can be set to the highest priority. The lists can be found in this folder: [resources/vocabulary](https://github.com/yoda-pa/yoda/tree/master/resources/vocabulary)
