### ISSUE TITLE
URL shortener not working

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#90]
## What are the steps to reproduce this issue?
1. While using Python 2:
  1. Install yoda
  1. Run `yoda url shorten <some url>`. This works fine
  1. RUn `yoda url expand <shortened url>`. Doesn't work
2. While using Python 3:
  1. Install yoda
  1. Run `yoda url shorten <some url>`. Doesn't work

## What happens?
It says command doesn't exist.
The tests are also failing because of this.

## What were you expecting to happen?
To shorten/expand URLs

## What versions of software are you using?
**Operating System:** Ubuntu 16.04

**Comment by skcse** [comment]
Is the below command is the way to install yoda using python3. if 'yes' then I think 'url shorten' and 'url expand' is working fine 
$ python3 -m venv venv3
$ . venv3/bin/activate
(venv3) $ pip install --editable .
![yoda_issues90](https://user-images.githubusercontent.com/18513941/38093557-f884b374-3388-11e8-918f-c796b02b386f.png)
